# Generated by Django 3.2.3 on 2021-07-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='paymentid',
            field=models.CharField(default='', max_length=300),
        ),
    ]
