# Generated by Django 3.2.3 on 2021-07-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razor_app', '0002_alter_donation_paymentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='id',
        ),
        migrations.AlterField(
            model_name='donation',
            name='paymentid',
            field=models.CharField(default='', max_length=300, primary_key=True, serialize=False),
        ),
    ]
